apiVersion: v1
kind: Secret
metadata:
  name: database-connection-args
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
data:
  DB_HOSTNAME: {{ "my-database.redis.svc.cluster.local" | b64enc }}
  DB_PORT: {{ "9001" | b64enc }}
  DB_PASSWORD: {{ "NGY4YTlhNGFkNGVjNzY4OGU2NGQzNjQ2" | b64enc }}